Let's consider only what's happening on the exponent of $e$ since the base is a constant and the issue with dimensionality happens just in the exponent, we have $ -\dfrac{1}{2}(x_n - \mu)^T\Sigma^{-1}(x_n-\mu)$

we can consider just the matrices opration for simplicty $(x_n - \mu)^T\Sigma^{-1}(x_n-\mu)$

$x_n, \mu \in \mathbb{R}^{d, 1}$ and $\Sigma^{-1} \in \mathbb{R}^{d, d}$ so when we evaluate the exponent $\overset{(d,1)}{{(x_n-\mu)}^T}$ we obtain a scalar

$\overset{(1, d) \times (d, d) \times (d, 1)}{{(x_n-\mu)}^T {\Sigma^{-1}}{(x_n-\mu)}^T}$

which is actually $(x_{n1} - \mu_1)^2\sigma_1 + (x_{n2} - \mu_2)^2\sigma_2 + ... + (x_{nd} - \mu_d)^2\sigma_d$

Now if we reason about the multi-sample case, in which we want to process all the $n$ data point at once, we can look at the dimenions of the exponent

we have $X \in \mathbb{R}^{n,d}, \mu \in \mathbb{R}^{d, 1}$ and $\Sigma^{-1} \in \mathbb{R}^{d, d}$ 

In [1]:
import numpy as np

In [2]:
x = np.array([[0, 1], [1, 1], [1, 2]])
x

array([[0, 1],
       [1, 1],
       [1, 2]])

In [3]:
mu = np.array([0.3, 0.2])
mu

array([0.3, 0.2])

In [4]:
x - mu

array([[-0.3,  0.8],
       [ 0.7,  0.8],
       [ 0.7,  1.8]])

In [5]:
x[0].shape

(2,)